apiVersion: v1
kind: Config
clusters:
- name: "do-custom"
  cluster:
    server: "https://rancher.134.122.29.85.sslip.io/k8s/clusters/c-m-dc4l9chw"
    certificate-authority-data: "xxxxxxxxxxxxxxxxxxxx"

users:
- name: "do-custom"
  user:
    token: "kubeconfig-user-xxxxxxxxxxxx:xxxxxxxxxxxxxxxxxxx"


contexts:
- name: "do-custom"
  context:
    user: "do-custom"
    cluster: "do-custom"
    # cluster: "do-custom"

current-context: "do-custom"
